name: Build vcpkg cache

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    name: Windows-Build
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -S . -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DSTOP_AFTER_VCPKG=ON
      env:
        VCPKG_BINARY_SOURCES: "clear;http,https://604f651a-6bcd-49cc-b256-2740663e4b03.ma.bw-cloud-instance.org/{triplet}-{name}-{sha},readwrite,Authorization: Token ${{ secrets.CACHING_SERVER_SECRET }}"
