# This is a basic workflow to help you get started with Actions

name: Cleanup old package versions

on:
  registry_package:
    types: [updated,published]
    
jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v3
        with:
          package-name: 'spdlog'
          min-versions-to-keep: 1
